name: project_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/totoro.jpg
    - assets/images/howl.png
    - assets/images/el-viento.jpg
    - assets/images/ponyo.jpg
    - assets/images/the-boys.jpeg
    - assets/images/tangled.jpeg
    - assets/images/zootopia.jpeg
    - assets/images/brave.jpeg
    - assets/images/frozen.jpg
    - assets/images/luca.jpg
    - assets/images/insideout2.png
    - assets/images/up.jpg
    - assets/images/encanto.jpg
    - assets/images/turningred.jpg
    - assets/images/onward.jpg
    - assets/images/elio.jpeg
    - assets/images/background.jpg
    - assets/images/avatar.jpg
    - assets/images/avatar2.jpg
    - assets/images/ant-man.jpg
    - assets/images/avenger-andgame.jpg
    - assets/images/black-panter.jpg
